title: Your awesome title
author: byBack
email: byback@xcom.com
description: > # this means to ignore newlines until "baseurl:"
  No more comments. Just run!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
